version: '3.8'

services:

  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hoytrabajas_app_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  db_data: