default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  database: hoytrabajas_app_development
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hoytrabajas_app_development

  
test:
  <<: *default
  database: hoytrabajas_app_test


production:
  <<: *default
  database: hoytrabajas_app_production
  username: hoytrabajas_app
  password: <%= ENV["HOYTRABAJAS_APP_DATABASE_PASSWORD"] %>
